#!/bin/bash
# /root/.bashrc (WSL)

init=$HOME/scripts

if [ -d "$init" ]; then
    for file in "${init}"/*.{sh,conf}; do
        [ -r "$file" ] && [ -f "$file" ] && . "$file"
    done
fi

[[ $- != *i* ]] && return

# Node Version Manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

export project="/mnt/g/.dev/sites/epk-2"
export sitedir="/mnt/g/.dev/sites"
export compdir="/mnt/g/.dev/sites/assets/components"
export assetdir="/mnt/g/.dev/sites/assets"
export fontdir="/mnt/g/.dev/sites/assets/fonts"
export C=/mnt/c
export F=/mnt/f
export G=/mnt/g

export workdir=$project


